name: CI Build & Upload

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 安装 Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: 安装依赖
        run: npm i

      - name: 构建
        run: npm run build

      - name: Clone quickjs
        run: git clone --depth 1 -b autorename https://github.com/xna00/quickjs.git
      
      - name: Install wine and mingw-w64
        run: |
          sudo apt update
          sudo apt install -y wine mingw-w64
          cp /usr/x86_64-w64-mingw32/lib/libwinpthread-1.dll .
        working-directory: ./quickjs

      - name: Setup Wine
        run: |
          wine --version
          winecfg /v
      
      - name: Build for Windows
        run: |
          make CONFIG_WIN32=y -j4
          cp ../dist/main.js ./
          wine qjsc.exe -e -o autorename.c main.js
          x86_64-w64-mingw32-gcc autorename.c libquickjs.a -o autorename.exe
          x86_64-w64-mingw32-strip autorename.exe
          cp autorename.exe ../dist/
        working-directory: ./quickjs

      - name: 上传构建产物
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/